//
//  vendors.c
//  iousbcap
//
//  Created by Sem Voigtländer on 19/02/20.
//  Copyright © 2020 kernelprogrammer. All rights reserved.
//

#include "vendors.h"
#include <string.h>
#include <stdlib.h>
mvusblib_vendor_desc_t VENDORS[UINT16_MAX] = {
    {USBVENDOR_FRYES_ELEC,"FRYES_ELEC"},
    {USBVENDOR_INGRAM,"INGRAM"},
    {USBVENDOR_CLUBMAC,"CLUBMAC"},
    {USBVENDOR_NE_FURNITURE_MART,"NE_FURNITURE_MART"},
    {USBVENDOR_PLANEX,"PLANEX"},
    {USBVENDOR_MICRONTEK,"MICRONTEK"},
    {USBVENDOR_DRAGONRISE,"DRAGONRISE"},
    {USBVENDOR_ASSMAN_ELEC,"ASSMAN_ELEC"},
    {USBVENDOR_BOEYE_TECH,"BOEYE_TECH"},
    {USBVENDOR_TRUST_INTTL,"TRUST_INTTL"},
    {USBVENDOR_IBP,"IBP"},
    {USBVENDOR_MLK,"MLK"},
    {USBVENDOR_TPLINK,"TPLINK"},
    {USBVENDOR_CHIPSBANK_MICRO_ELEC,"CHIPSBANK_MICRO_ELEC"},
    {USBVENDOR_HANGZHOU_WORLDE,"HANGZHOU_WORLDE"},
    {USBVENDOR_HUMAX_CO_LTD,"HUMAX_CO_LTD"},
    {USBVENDOR_MINI_AUTOMATION_CONTROLLER,"MINI_AUTOMATION_CONTROLLER"},
    {USBVENDOR_OCZ_TECH,"OCZ_TECH"},
    {USBVENDOR_OCZ_TECH_INC,"OCZ_TECH_INC"},
    {USBVENDOR_LTS,"LTS"},
    {USBVENDOR_SHENZHEN_SINOTE_TECHELEC,"SHENZHEN_SINOTE_TECHELEC"},
    {USBVENDOR_BERND_WALTER_COMPS_TECH,"BERND_WALTER_COMPS_TECH"},
    {USBVENDOR_INTEL,"INTEL"},
    {USBVENDOR_ENDPOINTS,"ENDPOINTS"},
    {USBVENDOR_THESYS_MICRO_ELEC,"THESYS_MICRO_ELEC"},
    {USBVENDOR_DATA_BROADCASTING_CORP,"DATA_BROADCASTING_CORP"},
    {USBVENDOR_ATMEL_CORP,"ATMEL_CORP"},
    {USBVENDOR_IWATSU_AMERICA,"IWATSU_AMERICA"},
    {USBVENDOR_MITEL_CORP,"MITEL_CORP"},
    {USBVENDOR_MITSUMI,"MITSUMI"},
    {USBVENDOR_HP_INC,"HP_INC"},
    {USBVENDOR_GENOA_TECH,"GENOA_TECH"},
    {USBVENDOR_OAK_TECH_INC,"OAK_TECH_INC"},
    {USBVENDOR_ADAPTEC_INC,"ADAPTEC_INC"},
    {USBVENDOR_DIEBOLD_INC,"DIEBOLD_INC"},
    {USBVENDOR_SIEMENS_ELECTROMECH,"SIEMENS_ELECTROMECH"},
    {USBVENDOR_EPSON_IMAGING_TECHCENTER,"EPSON_IMAGING_TECHCENTER"},
    {USBVENDOR_OPTI_INC,"OPTI_INC"},
    {USBVENDOR_ELITEGROUP_COMPS_SYS,"ELITEGROUP_COMPS_SYS"},
    {USBVENDOR_XILINX_INC,"XILINX_INC"},
    {USBVENDOR_FARALLON_COMNS,"FARALLON_COMNS"},
    {USBVENDOR_NATIONAL_SEMICOND_CORP,"NATIONAL_SEMICOND_CORP"},
    {USBVENDOR_NATIONAL_REGISTRY_INC,"NATIONAL_REGISTRY_INC"},
    {USBVENDOR_ALI_CORP,"ALI_CORP"},
    {USBVENDOR_FUTURE_TECH_DEV_INTL_LTD,"FUTURE_TECH_DEV_INTL_LTD"},
    {USBVENDOR_NCR_CORP,"NCR_CORP"},
    {USBVENDOR_SYNOPSYS_INC,"SYNOPSYS_INC"},
    {USBVENDOR_FUJITSU_ICL_COMPS,"FUJITSU_ICL_COMPS"},
    {USBVENDOR_FUJITSU_PERSONAL_SYS,"FUJITSU_PERSONAL_SYS"},
    {USBVENDOR_QUANTA_COMPS_INC,"QUANTA_COMPS_INC"},
    {USBVENDOR_NEC_CORP,"NEC_CORP"},
    {USBVENDOR_KODAK_CO,"KODAK_CO"},
    {USBVENDOR_WELTREND_SEMICOND,"WELTREND_SEMICOND"},
    {USBVENDOR_VTECH_COMPS_LTD,"VTECH_COMPS_LTD"},
    {USBVENDOR_VIA_TECH_INC,"VIA_TECH_INC"},
    {USBVENDOR_MCCI,"MCCI"},
    {USBVENDOR_ECHO_SPEECH_CORP,"ECHO_SPEECH_CORP"},
    {USBVENDOR_BUFFALO_INC,"BUFFALO_INC"},
    {USBVENDOR_AWARD_SOFT_INTL,"AWARD_SOFT_INTL"},
    {USBVENDOR_LEADTEK_RESEARCH_INC,"LEADTEK_RESEARCH_INC"},
    {USBVENDOR_GIGABYTE_TECH_LTD,"GIGABYTE_TECH_LTD"},
    {USBVENDOR_WINBOND_ELEC_CORP,"WINBOND_ELEC_CORP"},
    {USBVENDOR_SYMBIOS_LOGIC,"SYMBIOS_LOGIC"},
    {USBVENDOR_AST_RESEARCH,"AST_RESEARCH"},
    {USBVENDOR_SAMSUNG_INFOSYS_AMERICA_INC,"SAMSUNG_INFOSYS_AMERICA_INC"},
    {USBVENDOR_PHOENIX_TECH_LTD,"PHOENIX_TECH_LTD"},
    {USBVENDOR_DTV,"DTV"},
    {USBVENDOR_S3INC,"S3INC"},
    {USBVENDOR_CREATIVE_TECH_LTD,"CREATIVE_TECH_LTD"},
    {USBVENDOR_LCS_TELEGRAPHICS,"LCS_TELEGRAPHICS"},
    {USBVENDOR_CHIPS_AND_TECH,"CHIPS_AND_TECH"},
    {USBVENDOR_NOKIA_MOBILE_PHONES,"NOKIA_MOBILE_PHONES"},
    {USBVENDOR_ADI_SYS_INC,"ADI_SYS_INC"},
    {USBVENDOR_COMP_ACCESS_TECH_CORP,"COMP_ACCESS_TECH_CORP"},
    {USBVENDOR_MICROCHIP_TECH_INC,"MICROCHIP_TECH_INC"},
    {USBVENDOR_MOTOROLA_SEMICOND_HK_LTD,"MOTOROLA_SEMICOND_HK_LTD"},
    {USBVENDOR_INTEGRATED_DEVICE_TECH_INC,"INTEGRATED_DEVICE_TECH_INC"},
    {USBVENDOR_MOTOROLA_ELEC_TAIWAN_LTD,"MOTOROLA_ELEC_TAIWAN_LTD"},
    {USBVENDOR_ADVANCED_GRAVIS_COMP_TECH_LTD,"ADVANCED_GRAVIS_COMP_TECH_LTD"},
    {USBVENDOR_CIRRUS_LOGIC,"CIRRUS_LOGIC"},
    {USBVENDOR_ERICSSON_AUSTRIAN_AG,"ERICSSON_AUSTRIAN_AG"},
    {USBVENDOR_INTEL_CORP,"INTEL_CORP"},
    {USBVENDOR_INNOVATIVE_SEMICOND_INC,"INNOVATIVE_SEMICOND_INC"},
    {USBVENDOR_MICRONICS,"MICRONICS"},
    {USBVENDOR_ACER_INC,"ACER_INC"},
    {USBVENDOR_MOLEX_INC,"MOLEX_INC"},
    {USBVENDOR_SUN_MICROSYS_INC,"SUN_MICROSYS_INC"},
    {USBVENDOR_ITAC_SYS_INC,"ITAC_SYS_INC"},
    {USBVENDOR_UNISYS_CORP,"UNISYS_CORP"},
    {USBVENDOR_ALPS_ELECTRIC_INC,"ALPS_ELECTRIC_INC"},
    {USBVENDOR_SAMSUNG_INFOSYS_AMERICA_INC_434,"SAMSUNG_INFOSYS_AMERICA_INC_434"},
    {USBVENDOR_HYUNDAI_ELEC_AMERICA,"HYUNDAI_ELEC_AMERICA"},
    {USBVENDOR_TAUGAGREINING_HF,"TAUGAGREINING_HF"},
    {USBVENDOR_FRAMATOME_CONNECTORS_USA,"FRAMATOME_CONNECTORS_USA"},
    {USBVENDOR_ADVANCED_MICRO_DEVICES_INC,"ADVANCED_MICRO_DEVICES_INC"},
    {USBVENDOR_VOICE_TECH_GROUP,"VOICE_TECH_GROUP"},
    {USBVENDOR_LEXMARK_INTL_INC,"LEXMARK_INTL_INC"},
    {USBVENDOR_LG_ELEC_USA_INC,"LG_ELEC_USA_INC"},
    {USBVENDOR_RADISYS_CORP,"RADISYS_CORP"},
    {USBVENDOR_EIZO_NANAO_CORP,"EIZO_NANAO_CORP"},
    {USBVENDOR_WINBOND_SYS_LAB,"WINBOND_SYS_LAB"},
    {USBVENDOR_ERICSSON_INC,"ERICSSON_INC"},
    {USBVENDOR_GATEWAY_INC,"GATEWAY_INC"},
    {USBVENDOR_LUCENT_TECH_INC,"LUCENT_TECH_INC"},
    {USBVENDOR_NMB_TECH_CORP,"NMB_TECH_CORP"},
    {USBVENDOR_ANALOG_DEVICES_INC,"ANALOG_DEVICES_INC"},
    {USBVENDOR_MICROSOFT_CORP,"MICROSOFT_CORP"},
    {USBVENDOR_LOGITECH_INC,"LOGITECH_INC"},
    {USBVENDOR_APPLE_INC,"APPLE_INC"},
    {USBVENDOR_LINUX_FOUNDATION,"LINUX_FOUNDATION"},
    {USBVENDOR_QUALCOMM_OPTION,"QUALCOMM_OPTION"},
    {USBVENDOR_GENERIC,"GENERIC"},
    {USBVENDOR_UKERN_SOFTWARE,"UKERN_SOFTWARE"},
};

void mvusblib_vendor_string(mvusblib_vendor_t vendor, char* stringOut) {
    for(int i = 0; i < UINT16_MAX; i++) {
        if(VENDORS[i].vendor == vendor) {
            memcpy(stringOut, VENDORS[i].name, MAX_VENDORNAME);
            return;
        }
    }
    sprintf(stringOut, "UNKNOWN %#x", vendor);
}

mvusblib_vendor_t mvusblib_string_vendor(const char* vendorname) {
    for(int i = 0; i < UINT16_MAX; i++) {
        if(!strcmp(VENDORS[i].name, vendorname))
            return VENDORS[i].vendor;
    }
    return USBVENDOR_UNKNOWN;
}
